FROM node:18-alpine

RUN apk --update --no-cache add bash git less openssh gpgme

ENV APP_DIR /usr/app
RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR

COPY package.json yarn.lock ./
RUN yarn install --no-progress

CMD tail -f /dev/null
