version: "3.7"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.development
    logging:
      options:
        max-file: "3"
        max-size: "10m"
    volumes:
      - .:/usr/app
      - app-node-modules:/usr/app/node_modules
    ports:
      - '6060:6060'
      - '10229:9229'

  postgres_db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    logging:
      options:
        max-file: "3"
        max-size: "10m"
    ports:
      - '5438:5432'
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data

volumes:
  # Keep a separate virtual volume for app's node_module directory to persist its content
  app-node-modules: {}